---
title: "Chapter 3 Retrieve Data From a Single Table"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
author: Jianyuan(Andy) Hu
format: 
  html:
    # https://github.com/quarto-dev/quarto-cli/issues/6645
    # darkly and arrow seems work well for SQL documents
    theme: darkly
    highlight-style: arrow
    revealjs: arrow
    toc: TRUE
    toc-location: left
    fontsize: "14"
    code-fold: false
    df-print: paged
    embed-resources: true
---

```{r, echo=FALSE, warning=FALSE}
library(odbc)
library(DBI)
conn <- dbConnect(
  drv = odbc(),
  dsn = "Local Teaching MySQL84"
)

dbListTables(conn = conn)

# "https://yihui.org/knitr/options/"
library(knitr)
opts_chunk$set(connection = conn)
# row.print works for R chucks, max.print works for SQL chucks
opts_chunk$set(max.print = 15)
```

# Reference

This example is based on Murach, J. (2023). Murach’s MySQL (4th Edition).

```{sql}
SELECT * 
FROM ap.invoices
```


```{sql}
SELECT invoice_number, invoice_date, invoice_total
FROM ap.invoices
ORDER BY invoice_total DESC
```


```{sql}
SELECT invoice_id, invoice_total,
       credit_total + payment_total AS total_credits
FROM ap.invoices
WHERE invoice_id = 17
```
```{sql}
SELECT invoice_number, invoice_date, invoice_total
FROM ap.invoices
WHERE invoice_date BETWEEN '2022-06-01' AND '2022-06-30'
ORDER BY invoice_date
```

```{sql}
SELECT CONCAT(invoice_id, '-', vendor_id) AS combo
FROM ap.invoices
```

```{sql}
SELECT invoice_id, 
       invoice_id / 3 AS decimal_quotient,
       invoice_id DIV 3 AS integer_quotient,
       invoice_id % 3 AS remainder
FROM ap.invoices
ORDER BY invoice_id
```

```{sql}
SELECT vendor_contact_first_name, vendor_contact_last_name,
       CONCAT(LEFT(vendor_contact_first_name, 1), 
              LEFT(vendor_contact_last_name, 1)) AS initials
FROM ap.vendors
```

```{sql}
SELECT invoice_date,
  DATE_FORMAT(invoice_date, '%m/%d/%y') AS 'MM/DD/YY',
  DATE_FORMAT(invoice_date, '%e-%b-%Y') AS 'DD-Mon-YYYY',
  DATE_FORMAT(invoice_date, '%b') AS 'Mon'
FROM ap.invoices
ORDER BY invoice_date
```
```{sql}
SELECT invoice_date, invoice_total,
       ROUND(invoice_total) AS nearest_dollar,
       ROUND(invoice_total, 1) AS nearest_dime
FROM ap.invoices
ORDER BY invoice_date
```

```{sql}
SELECT DISTINCT vendor_city, vendor_state
FROM ap.vendors
ORDER BY vendor_city
```

```{sql}
SELECT vendor_city, vendor_state
FROM ap.vendors
ORDER BY vendor_city
```

```{sql}
SELECT *
FROM ap.vendors
LIMIT 17, 10
```

```{r}
dbDisconnect(conn)
```

